-- Users & Roles
CREATE TABLE IF NOT EXISTS users (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(190) NOT NULL UNIQUE,
	name VARCHAR(190) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	role ENUM('ADMIN','INVESTOR','ADVISOR') NOT NULL DEFAULT 'INVESTOR',
	phone VARCHAR(50) NULL,
	is_active TINYINT(1) NOT NULL DEFAULT 1,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS investor_profiles (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT UNSIGNED NOT NULL UNIQUE,
	address VARCHAR(255) NULL,
	national_id VARCHAR(100) NULL,
	rdn_account VARCHAR(100) NULL,
	bank_name VARCHAR(100) NULL,
	bank_account_enc TEXT NULL,
	bank_account_iv VARCHAR(64) NULL,
	kyc_status ENUM('PENDING','VERIFIED','REJECTED') NOT NULL DEFAULT 'PENDING',
	kyc_verified_at DATETIME NULL,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Stocks (IDX)
CREATE TABLE IF NOT EXISTS stocks (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	symbol VARCHAR(16) NOT NULL,
	name VARCHAR(190) NULL,
	UNIQUE(symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stock_trades (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	investor_id BIGINT UNSIGNED NOT NULL,
	stock_id BIGINT UNSIGNED NOT NULL,
	trade_type ENUM('BUY','SELL') NOT NULL,
	lots INT NOT NULL,
	price DECIMAL(18,2) NOT NULL,
	fee DECIMAL(18,2) NOT NULL DEFAULT 0,
	trade_date DATE NOT NULL,
	FOREIGN KEY (investor_id) REFERENCES investor_profiles(id) ON DELETE CASCADE,
	FOREIGN KEY (stock_id) REFERENCES stocks(id) ON DELETE CASCADE,
	INDEX investor_date (investor_id, trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Derived positions for quick dashboard (can be maintained via triggers/jobs)
CREATE TABLE IF NOT EXISTS stock_positions (
	investor_id BIGINT UNSIGNED NOT NULL,
	stock_id BIGINT UNSIGNED NOT NULL,
	quantity INT NOT NULL DEFAULT 0,
	avg_price DECIMAL(18,2) NOT NULL DEFAULT 0,
	PRIMARY KEY (investor_id, stock_id),
	FOREIGN KEY (investor_id) REFERENCES investor_profiles(id) ON DELETE CASCADE,
	FOREIGN KEY (stock_id) REFERENCES stocks(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dividends
CREATE TABLE IF NOT EXISTS dividends (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	stock_id BIGINT UNSIGNED NULL,
	investor_id BIGINT UNSIGNED NOT NULL,
	type ENUM('CASH','STOCK') NOT NULL DEFAULT 'CASH',
	amount DECIMAL(18,2) NOT NULL DEFAULT 0,
	share_qty INT NULL,
	dividend_date DATE NOT NULL,
	FOREIGN KEY (investor_id) REFERENCES investor_profiles(id) ON DELETE CASCADE,
	FOREIGN KEY (stock_id) REFERENCES stocks(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Family capital deposits/withdrawals
CREATE TABLE IF NOT EXISTS family_capital (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	investor_id BIGINT UNSIGNED NOT NULL,
	type ENUM('DEPOSIT','WITHDRAWAL') NOT NULL,
	amount DECIMAL(18,2) NOT NULL,
	note VARCHAR(255) NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (investor_id) REFERENCES investor_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Logs
CREATE TABLE IF NOT EXISTS activity_logs (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT UNSIGNED NULL,
	action VARCHAR(190) NOT NULL,
	entity_type VARCHAR(190) NULL,
	entity_id BIGINT UNSIGNED NULL,
	meta JSON NULL,
	ip VARCHAR(64) NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tax documents & files
CREATE TABLE IF NOT EXISTS documents (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	investor_id BIGINT UNSIGNED NULL,
	category ENUM('TAX','MINUTES','CONTRACT','OTHER') NOT NULL,
	title VARCHAR(190) NOT NULL,
	path VARCHAR(190) NOT NULL,
	uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (investor_id) REFERENCES investor_profiles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Settings
CREATE TABLE IF NOT EXISTS settings (
	id TINYINT PRIMARY KEY DEFAULT 1,
	company_name VARCHAR(190) NULL,
	recaptcha_site_key VARCHAR(190) NULL,
	recaptcha_secret VARCHAR(190) NULL,
	smtp_host VARCHAR(190) NULL,
	smtp_port INT NULL,
	smtp_user VARCHAR(190) NULL,
	smtp_pass VARCHAR(190) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Ownership shares for family-wide distributions
CREATE TABLE IF NOT EXISTS ownership_shares (
	investor_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
	share_percent DECIMAL(6,4) NOT NULL DEFAULT 0,
	FOREIGN KEY (investor_id) REFERENCES investor_profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Generic distributions (e.g., business profit sharing)
CREATE TABLE IF NOT EXISTS distributions (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	label VARCHAR(100) NOT NULL,
	total_amount DECIMAL(18,2) NOT NULL,
	distributed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS distribution_lines (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	distribution_id BIGINT UNSIGNED NOT NULL,
	investor_id BIGINT UNSIGNED NOT NULL,
	share_percent DECIMAL(6,4) NOT NULL,
	amount DECIMAL(18,2) NOT NULL,
	FOREIGN KEY (distribution_id) REFERENCES distributions(id) ON DELETE CASCADE,
	FOREIGN KEY (investor_id) REFERENCES investor_profiles(id) ON DELETE CASCADE,
	INDEX(distribution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Add optional 2FA OTP fields to users
ALTER TABLE users
	ADD COLUMN IF NOT EXISTS otp_code VARCHAR(10) NULL,
	ADD COLUMN IF NOT EXISTS otp_expires_at DATETIME NULL;

ALTER TABLE stock_trades
	ADD COLUMN IF NOT EXISTS realized_pl DECIMAL(18,2) NULL;